before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: TSSfSSNnj1Pk5BlFAN5RECabiJlJF5WJ7LAqXW4y8ZUGRhv50UpDDI7Qa0Ewqb1XkQ4OQhczlptAMXMMs93S8cmd2ycybrhGdRmyPU3OuxIOOS9NRWNVinTJMfUqtQUhKN7+TOeaFOUOgodeEHsnQC3UouGI9cBOwOun6O2eW9hpjA8ZEwZKlk76Apz3jamiSHQ5S+bTDjQxT83cgmMWjqlGEY/R8vaneD0pVoXlhh7uTw3sJFE3B6jR0hlf/MBDBly0Wq4C0FopXT8qhWHALyewbchYq/AHt/Ot2jmdlOsgtcS0zDKHOajtf74KL8H2cSx/99D7rLcUcX3vN4SaLlWNYhlIAofcgMOF5IP+/qHqMoZjy6J0mc34A319z+jNDJklRkL6hCukEzDCH+ndo9LvmQQAqCO5SessJSiFY8+PhEgfRLIpD1QPixXNe1VDVFQ1+g316S1iNX5xmQg7q88A+eUVwDEyODo7phObl0ipZ8HkwzFjO/mp9hs4WfHjfZLS/Uz0NgOonc0Nm4JqVP211u3IcMApoisL85WWl4k+3dGZCeySIi2SyAq2YAe0+S7l8/OLK55NTo9BnBGW0UszUy6RcPkEGGpZvWJ7W5kGOeHje+mVdzpFdN0AnGUAj1H2xH/q/WIH0xmIb+S0SHQ+GXLLXKgRaP3R6OgHSCU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
